// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AccessoryImage
{
    public long ImageId { get; set; }

    public long? AccessoryId { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsPrimary { get; set; }

    public virtual Accessory Accessory { get; set; }
}