// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Accessory : BaseEntity
{
    [Key]

    public int AccessoryId { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? StockQuantity { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AccessoryImage> AccessoryImages { get; set; } = new List<AccessoryImage>();

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Terrarium> Terraria { get; set; } = new List<Terrarium>();
}