// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AddressDelivery
{
    public int Id { get; set; }

    public int OrderId { get; set; } // text(250)

    public string ReceiverName { get; set; } // text(250)

    public string ReceiverPhone { get; set; } // text(250)

    public string ReceiverAddress { get; set; } // text(250)

    public int UserId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public DateTime ModifiedOnUtc { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Order Order { get; set; }
}