// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AddressDelivery
{
    public long AddressDeliveryId { get; set; }

    public long? OrderId { get; set; }

    public string AddressLine { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string PostalCode { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverPhone { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}