// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Address
{
    public int AddressId { get; set; }

    public int? UserId { get; set; }

    public string AddressLine { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string PostalCode { get; set; }

    public bool? IsDefault { get; set; }

    public virtual User User { get; set; }
}