// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AddressDelivery : BaseEntity
{
    [Key]

    public int AddressDeliveryId { get; set; }

    public int OrderId { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string PostalCode { get; set; }

    public string PhoneNumber { get; set; }

    public string RecipientName { get; set; }

    public virtual Order Order { get; set; }
}