// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AiSuggestLayout
{
    public long SuggestionId { get; set; }

    public long? PersonalizeId { get; set; }

    public long? UserId { get; set; }

    public long? TerrariumId { get; set; }

    public long? LayoutId { get; set; }

    public string SuggestionDetails { get; set; }

    public decimal? ConfidenceScore { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual LayoutTerrarium Layout { get; set; }

    public virtual Personalize Personalize { get; set; }

    public virtual Terrarium Terrarium { get; set; }

    public virtual User User { get; set; }
}