// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class AiSuggestLayout
{
    public int SuggestionId { get; set; }

    public int? PersonalizeId { get; set; }

    public int? UserId { get; set; }

    public int? TerrariumId { get; set; }

    public int? LayoutId { get; set; }

    public string SuggestionDetails { get; set; }

    public decimal? ConfidenceScore { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual LayoutTerrarium Layout { get; set; }

    public virtual Personalize Personalize { get; set; }

    public virtual Terrarium Terrarium { get; set; }

    public virtual User User { get; set; }
}