// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Blog : BaseEntity
{
    [Key]

    public int BlogId { get; set; }

    public int UserId { get; set; }

    public int BlogCategoryId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }
    public string Status { get; set; }

    public virtual BlogCategory BlogCategory { get; set; }

    public virtual User User { get; set; }
}