// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Blog
{
    public int BlogId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? AuthorId { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public int? Views { get; set; }

    public virtual User Author { get; set; }

    public virtual BlogCategory Category { get; set; }
}