// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class FeedbackImage
{
    public long ImageId { get; set; }

    public long? FeedbackId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual Feedback Feedback { get; set; }
}