// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class LayoutTerrarium
{
    public int LayoutTerrariumId { get; set; }

    public int TerrariumVariantId { get; set; }

    public string LayoutData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual TerrariumVariant TerrariumVariant { get; set; }
}