// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class LayoutTerrarium
{
    public long LayoutId { get; set; }

    public long? TerrariumId { get; set; }

    public string LayoutName { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<AiSuggestLayout> AiSuggestLayouts { get; set; } = new List<AiSuggestLayout>();

    public virtual Terrarium Terrarium { get; set; }
}