// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using TerrariumGardenTech.Repositories.Enums;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Membership
{
    public int MembershipId { get; set; }

    public int UserId { get; set; }

    public decimal Price { get; set; }
    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    [NotMapped]
    public MembershipStatus StatusEnum
    {
        get => Enum.TryParse<MembershipStatus>(Status, out var result) ? result : MembershipStatus.Expired;
        set => Status = value.ToString();
    }

    public virtual User User { get; set; }


}