// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Notification : BaseEntity
{
    [Key]
    public int NotificationId { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public string Message { get; set; }
    public bool? IsRead { get; set; }
    public DateTime? CreatedAt { get; set; }
    [ForeignKey(nameof(UserId))]
    public virtual User User { get; set; }
}