// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Order
{
    public int OrderId { get; set; }

    public int? UserId { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public decimal? ShippingFee { get; set; }

    public int? VoucherId { get; set; }

    public int? AddressDeliveryId { get; set; }

    public virtual ICollection<AddressDelivery> AddressDeliveries { get; set; } = new List<AddressDelivery>();

    public virtual AddressDelivery AddressDelivery { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<ReturnExchangeRequest> ReturnExchangeRequests { get; set; } = new List<ReturnExchangeRequest>();

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}