// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Order : BaseEntity
{
    [Key]

    public int OrderId { get; set; }

    public int UserId { get; set; }

    public int? VoucherId { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? Deposit { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public string PaymentStatus { get; set; }

    public string ShippingStatus { get; set; }

    public virtual ICollection<AddressDelivery> AddressDeliveries { get; set; } = new List<AddressDelivery>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PaymentTransition> PaymentTransitions { get; set; } = new List<PaymentTransition>();

    public virtual ICollection<ReturnExchangeRequest> ReturnExchangeRequests { get; set; } = new List<ReturnExchangeRequest>();

    public virtual ICollection<ShippingDetail> ShippingDetails { get; set; } = new List<ShippingDetail>();

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}