// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class OrderItemDetail
{
    public long DetailId { get; set; }

    public long? OrderItemId { get; set; }

    public long? TerrariumVariantId { get; set; }

    public string CustomDetails { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual TerrariumVariant TerrariumVariant { get; set; }
}