// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class OrderItemDetail
{
    public int OrderItemDetailId { get; set; }
    public int OrderItemId { get; set; }
    public string DetailKey { get; set; }
    public string DetailValue { get; set; }
    public int Quantity { get; set; }  
    public decimal UnitPrice { get; set; }  
    public virtual OrderItem OrderItem { get; set; }
}