// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class PaymentTransaction
{
    public int TransactionId { get; set; }

    public int? OrderId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string Status { get; set; }

    public string GatewayResponse { get; set; }

    public virtual Order Order { get; set; }
}