// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Personalize
{
    public int PersonalizeId { get; set; }

    public int UserId { get; set; }

    public string Preferences { get; set; }

    public string Theme { get; set; }

    public string Language { get; set; }

    public virtual User User { get; set; }
}