// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Personalize : BaseEntity
{
    [Key]
    public int PersonalizeId { get; set; }
    public int UserId { get; set; }
    public string Type { get; set; }
    public string Shape { get; set; }
    public string TankMethod { get; set; }
    public string Theme { get; set; }
    public string Language { get; set; }
    [ForeignKey(nameof(UserId))]
    public virtual User User { get; set; }
}