// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class PromotionTerrariumVariant  : BaseEntity
{
    [Key]

    public int PromotionTerrariumVariantId { get; set; }

    public int PromotionId { get; set; }

    public int TerrariumVariantId { get; set; }

    public decimal? DiscountPercent { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual TerrariumVariant TerrariumVariant { get; set; }
}