// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class PromotionTerrariumVariant
{
    public long PromotionVariantId { get; set; }

    public long? PromotionId { get; set; }

    public long? TerrariumVariantId { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual TerrariumVariant TerrariumVariant { get; set; }
}