// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class ReturnExchangeRequestItem
{
    public int RequestItemId { get; set; }

    public int? RequestId { get; set; }

    public int? OrderItemId { get; set; }

    public int Quantity { get; set; }

    public string Reason { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual ReturnExchangeRequest Request { get; set; }
}