// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class ShippingDetail : BaseEntity
{
    [Key]

    public int ShippingDetailId { get; set; }

    public int OrderId { get; set; }

    public string ShippingMethod { get; set; }

    public decimal? ShippingCost { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public string TrackingNumber { get; set; }

    [ForeignKey(nameof(OrderId))]
    public virtual Order Order { get; set; }
}