// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class ShippingDetail
{
    public int ShippingDetailId { get; set; }

    public int OrderId { get; set; }

    public string ShippingMethod { get; set; }

    public decimal? ShippingCost { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public string TrackingNumber { get; set; }

    public virtual Order Order { get; set; }
}