// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Terrarium : BaseEntity
{
    [Key]

    public int TerrariumId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int Stock { get; set; }

    public string Status { get; set; }

    public string Type { get; set; }

    public string Shape { get; set; }

    public string TankMethod { get; set; }

    public string Theme { get; set; }

    public int? AccessoryId { get; set; }

    public string Size { get; set; }

    public string bodyHTML { get; set; }

    public virtual Accessory Accessory { get; set; }

    public virtual ICollection<TerrariumImage> TerrariumImages { get; set; } = new List<TerrariumImage>();

    public virtual ICollection<TerrariumVariant> TerrariumVariants { get; set; } = new List<TerrariumVariant>();
}