// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Terrarium
{
    public int TerrariumId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Stock { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AiSuggestLayout> AiSuggestLayouts { get; set; } = new List<AiSuggestLayout>();

    public virtual TerrariumCategory Category { get; set; }

    public virtual ICollection<LayoutTerrarium> LayoutTerraria { get; set; } = new List<LayoutTerrarium>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<TerrariumImage> TerrariumImages { get; set; } = new List<TerrariumImage>();

    public virtual ICollection<TerrariumVariant> TerrariumVariants { get; set; } = new List<TerrariumVariant>();
}