// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class TerrariumVariant
{
    public long VariantId { get; set; }

    public long? TerrariumId { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public decimal? PriceAdjustment { get; set; }

    public int Stock { get; set; }

    public virtual ICollection<OrderItemDetail> OrderItemDetails { get; set; } = new List<OrderItemDetail>();

    public virtual ICollection<PromotionTerrariumVariant> PromotionTerrariumVariants { get; set; } = new List<PromotionTerrariumVariant>();

    public virtual Terrarium Terrarium { get; set; }
}