// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class TerrariumImage : BaseEntity
{
    [Key]

    public int TerrariumImageId { get; set; }

    public int TerrariumId { get; set; }

    public string ImageUrl { get; set; }

    public string AltText { get; set; }

    public bool? IsPrimary { get; set; }

    public virtual Terrarium Terrarium { get; set; }
}