// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public int? UserId { get; set; }

    public string Code { get; set; }

    public decimal DiscountValue { get; set; }

    public string DiscountType { get; set; }

    public decimal? MinOrderValue { get; set; }

    public decimal? MaxDiscountValue { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}