// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Address
{
    public int Id { get; set; }

    public string TagName { get; set; } // max length 250

    public int UserId { get; set; }

    public string ReceiverName { get; set; } // max length 250

    public string ReceiverPhone { get; set; } // max length 250

    public string ReceiverAddress { get; set; } // max length 250

    public bool IsDefault { get; set; } // true or false

    public virtual User User { get; set; }
}