// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Address
{
    public int AddressId { get; set; }

    public string TagName { get; set; } // max length 250

    public int UserId { get; set; }

    public string ReceiverName { get; set; } // max length 250

    public string ReceiverPhone { get; set; } // max length 250

    public string ReceiverAddress { get; set; } // max length 250
    public string ProvinceCode { get; set; }    // Thêm
    public string DistrictCode { get; set; }    // Thêm
    public string WardCode { get; set; }        // Thêm
    // ✅ Toạ độ dạng string
    public string Latitude { get; set; }   // Vĩ độ
    public string Longitude { get; set; }  // Kinh độ
    public bool IsDefault { get; set; } // true or false

    public virtual User User { get; set; }
}