// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using TerrariumGardenTech.Common.Entity;
using TerrariumGardenTech.Common.Enums;

using TerrariumGardenTech.Common.Enums;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }
    public int? AddressId { get; set; }
    public int? VoucherId { get; set; }

    public decimal TotalAmount { get; set; }
    public decimal? DiscountAmount { get; set; }
    public decimal? Deposit { get; set; }

    public DateTime? OrderDate { get; set; }

    public OrderStatusEnum Status { get; set; }

    public string PaymentStatus { get; set; }
    
    public string TransactionId { get; set; }

    //public string ShippingStatus { get; set; }
    //// Thêm thuộc tính PaymentMethod để lưu phương thức thanh toán
    //public string PaymentMethod { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payment { get; set; } = new List<Payment>();


    public virtual User User { get; set; }
    public virtual Address Address { get; set; }   // Navigation property mới

    public virtual Voucher Voucher { get; set; }

    public virtual ICollection<OrderTransport> Transports { get; set; } = new List<OrderTransport>();
    public virtual ICollection<OrderRequestRefund> Refunds { get; set; } = new List<OrderRequestRefund>();
}