// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using TerrariumGardenTech.Common.Entity;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int OrderId { get; set; }
    public int? TerrariumId { get; set; }

    public int? AccessoryId { get; set; }

    public int? TerrariumVariantId { get; set; }
    // Các thông tin số lượng riêng biệt
    public int? AccessoryQuantity { get; set; } // Số lượng phụ kiện
    public int? TerrariumVariantQuantity { get; set; } // Số lượng terrarium

    public int? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }
    public int? ComboId { get; set; }
    public string ItemType { get; set; } = "Single";
    public string? ComboSnapshot { get; set; } // JSON snapshot

    // Navigation Properties
    public virtual Combo? Combo { get; set; }

    public virtual Accessory Accessory { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Order Order { get; set; }


    public virtual TerrariumVariant TerrariumVariant { get; set; }
}