// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TerrariumGardenTech.Common.Entity;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Personalize
{
    [Key]

    public int PersonalizeId { get; set; }

    public int UserId { get; set; }
    public int EnvironmentId { get; set; }
    public int TankMethodId { get; set; }
    public int ShapeId { get; set; }
    [ForeignKey(nameof(UserId))]
    public virtual User User { get; set; }

    public virtual TankMethod TankMethods { get; set; }
    public virtual EnvironmentTerrarium Environment { get; set; }
    public virtual Shape Shapes { get; set; }
}