// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class TerrariumVariant
{
    public int TerrariumVariantId { get; set; }

    public int TerrariumId { get; set; }

    public string VariantName { get; set; }

    public decimal Price { get; set; }

    public int StockQuantity { get; set; }
    public string UrlImage { get; set; }
    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; } = DateTime.Now;


    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PromotionTerrariumVariant> PromotionTerrariumVariants { get; set; } = new List<PromotionTerrariumVariant>();

    public virtual Terrarium Terrarium { get; set; }
}