// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrariumGardenTech.Repositories.Entity;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? DiscountPercent { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public string Status { get; set; }

    public int TotalUsage { get; set; }         // Tổng lượt cấp phát
    public int RemainingUsage { get; set; }     // Lượt còn lại
    public bool IsPersonal { get; set; }        // Voucher cá nhân?
    public string? TargetUserId { get; set; }   // User đích (nếu cá nhân)
    public int? PerUserUsageLimit { get; set; } // Giới hạn mỗi user


    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
    public virtual ICollection<VoucherUsage> VoucherUsages { get; set; } = new List<VoucherUsage>();
}